### ISSUE TITLE
Error when joining two nodes

### ISSUE THREAD

**Issue by timbuchwaldt** [rabbitmq/ra#118]
Hey!
We are observing some strange behaviour when joining two nodes, doing the following:
- Create 2 Erlang/Elixir nodes named `alpha` and `beta`
- Run `:ra.start_or_restart_cluster(:sm, {:module, Our.Raft, %{}}, [{:sm, node()}])` on both
- Run `:ra.add_member(:sm, {:sm, :beta@localhost})` on `alpha`

Expected behaviour: 
The nodes are joined and form a 2 node cluster

Actual behaviour: 
Sometimes the nodes form the cluster, sometimes they error out with `leader saw append_entries_rpc for same term 1 this should not happen!` on `beta`.

This can be fixed by running `:ra.add_member(:sm, {:sm, :alpha@localhost})` on `beta` - it seems like during the connection process the `leader saw append_entries_rpc for same term 1 this should not happen!` crash interrupts the cluster formation. This also shows in `:ra.members/2` showing both nodes on `alpha`, just `beta` itself on `beta`.

**Comment by timbuchwaldt** [comment]
Update: It seems a bit worse: I have different histories on both nodes after joining from both sides. Newly added commands are correctly processed, but the system is in a state where `ra` is happy, accepts new writes, has a fully formed cluster - and still differing histories on both sides.

**Comment by kjnilsson** [comment]
what you are doing in your first step is starting two one node clusters then trying to join them. This can never work as they both enter leadership state when you start them (being one node clusters).

If you want to add a member to a cluster you need to pass it an initial cluster that includes the other node(s) you want to join them to. This way they cannot become leaders of their own cluster.

**Comment by timbuchwaldt** [comment]
I was almost sure I'm holding it wrong - and it works now, thank you! :)

Just for verification: I now reset the local server (`:ra.force_delete_server/1`), then start a new one (`:ra.start_server/1`), then ask an existing cluster node to join my  local node (`:ra.add_member/2`).

**Comment by michaelklishin** [comment]
@timbuchwaldt can we close this issue? We'd welcome a doc PR, by the way.

**Comment by kjnilsson** [comment]
Yes the issue here is using the `*start_cluster` apis that will assume the initial cluster is a valid cluster and will attempt to "start" it by trigger and initial elections. `ra:start_server` will not trigger an election and would thus be safe to use when growing a cluster from a single member.

**Comment by timbuchwaldt** [comment]
Yep, this seems to work reliably now :) I'll have a look at the docs, closing for now. Thx :)
