### ISSUE TITLE
How to do snapshot when there are many files

### ISSUE THREAD

**Issue by jinshuaiyu2** [rabbitmq/ra#124]
Our team is doing some experiments with the ra module, we need to take a snapshot of many files, how to achieve a ra_snapshot behaviour?

**Comment by kjnilsson** [comment]
You can write a custom snapshotter by implementing the `ra_snapshot` behaviour: https://github.com/rabbitmq/ra/blob/master/src/ra_snapshot.erl

This is still somewhat experimental and may be subject to API change but should be relatively stable.

**Comment by michaelklishin** [comment]
@kjnilsson we need a forum for Ra ;)
