### ISSUE TITLE
Docs out of sync?

### ISSUE THREAD

**Issue by koudelka** [rabbitmq/ra#129]
Hey, I just noticed that the edocs appear to be out of sync. 

Specifically, I was looking at [`ra_machine:state_enter/3`](https://rabbitmq.github.io/ra/ra_machine.html#state_enter-3), which seems to take two arguments [in the source docs](https://github.com/rabbitmq/ra/blob/master/src/ra_machine.erl#L20).

**Comment by kjnilsson** [comment]
That is the function spec for the exported function in the `ra_machine` module. The callback you need to implement only needs two.

**Comment by koudelka** [comment]
Ah, duh! Sorry about that.
