### ISSUE TITLE
what time use Raft in rabbitmq?

### ISSUE THREAD

**Issue by WithLin0510** [rabbitmq/ra#15]
![image](https://user-images.githubusercontent.com/22409551/38188561-1330eaea-368f-11e8-8787-6a68e5a1236f.png)

![image](https://user-images.githubusercontent.com/22409551/38188609-43d2b8ae-368f-11e8-9e16-38d9f0e884d1.png)

![image](https://user-images.githubusercontent.com/22409551/38188626-52999678-368f-11e8-9261-86ff519c4f6f.png)

What time use Raft in rabbitmq?

**Comment by kjnilsson** [comment]
Hi,

I'm not sure I understand your question. We don't use github issues for discussion soiIf you want to discuss anything RabbitMQ related please use the rabbitmq-users mailing list. 

https://groups.google.com/forum/?nomobile=true#!forum/rabbitmq-users

**Comment by michaelklishin** [comment]
We gave [a talk about some of the reasons for adopting Raft](https://www.youtube.com/watch?v=w-_1Wwymk58) in December last year.
