### ISSUE TITLE
Cluster Splitting?

### ISSUE THREAD

**Issue by koudelka** [rabbitmq/ra#152]
Hey there!

I've got a use-case where a cluster is handling a range of keys, and I'd like to be able to split it into two clusters, each handling one half of the range.

In theory, I'd add new cluster members as followers, let them catch up, then instruct the cluster to split the new members into a new cluster. The general hope being that the initial cluster could service requests while the new members are catching up. (Of course, I'd be handling all of the application-specific routing, etc...)

I suspect this isn't really a sensible feature to hope for, given the complexity involved, but I thought I'd ask if you folks were planning such a thing for your rabbitmq use-case.

Thanks so much for the brilliant library. :)

**Comment by michaelklishin** [comment]
We are not. #44 and #139 cover two different ways to reach "multitenancy".
