### ISSUE TITLE
Make snapshot data dir separately configurable from WAL data dir

### ISSUE THREAD

**Issue by zambal** [rabbitmq/ra#158]
Currently snapshots are written alongside WAL files in the same directory. If the data dir for snapshots would be separately configurable from the WAL files data dir, one could choose to store the WAL files on fast stable storage (or even a RAM disk, if durability requirements allow for this) while storing the snapshots on slower stable storage.

This would give ra users an extra option tuning ra for their use case.

**Comment by michaelklishin** [comment]
It sounds like a low hanging contribution fruit ;) The default would have to stay the same for backwards compatibility.

**Comment by kjnilsson** [comment]
You can already configure a separate location for the WAL. See the `wal_data_dir` configuration here: https://github.com/rabbitmq/ra/blob/master/src/ra_env.erl#L31

It does look like we missed to document that in the README though. :)

**Comment by zambal** [comment]
Thanks for the suggestion, that's exactly what I was looking for. I just submitted a pull request that documents this setting in the README.
