### ISSUE TITLE
delete_cluster and :dets closing

### ISSUE THREAD

**Issue by DarkMarmot** [rabbitmq/ra#162]
Hi, my team is trying to evaluate ra for use in our current project and are encountering a strange issue when we perform minimal tests. Following the ra_examples repo, we start a cluster, but when we test delete_cluster, we see :dets logs that complain that :dets was not properly closed.

Any idea you have as to what we might be doing wrong or if there's something we need to do to make sure that :dets closes properly would be duly appreciated, thanks!

**Comment by michaelklishin** [comment]
@DarkMarmot I'm sorry but you haven't provided any relevant information (no code, no complete stack traces, no logs). Our team does not speculate, it's too expensive. Please help us help you or you are on your own.
