### ISSUE TITLE
Floats and determinism

### ISSUE THREAD

**Issue by wanton7** [rabbitmq/ra#163]
I'm not sure if I have understood Raft algorithm correctly but it's basically similar to deterministic lockstep in games right? Because floats might be calculated differently in different computers, does that mean you shouldn't use floats with Raft?

Also what's best literature to learn about Raft algorithm? Is it this https://web.stanford.edu/~ouster/cgi-bin/papers/OngaroPhD.pdf

**Comment by michaelklishin** [comment]
The best source is the [Raft website](https://raft.github.io). The thesis is more extensive compared to the original paper.

I see some similarities in that [Deterministic Lockstep](https://gafferongames.com/post/deterministic_lockstep/) transfers state transitions. With Raft they can be anything, it really doesn't care if they involve floats or not.

I suggest you direct your Raft questions to the [Raft mailing list](https://groups.google.com/forum/#!forum/raft-dev).

**Comment by michaelklishin** [comment]
Someone asked "what good a raft is if it cannot float" 😆

**Comment by wanton7** [comment]
:smiley:
What I mean that if you do float calculations in different machines and their float implementation is different you'll get different results on different machine. That's why to games that use deterministic lockstep can't use floats on PC.  So I would expect same would apply here. But I'll ask about that on that Raft mailing list later.

**Comment by michaelklishin** [comment]
Raft only ensures that the log of operations is making consistent and safely replicated under certain conditions (the majority of nodes online). How the transitions are applied on each node and why is up to you.
