### ISSUE TITLE
Monitoring/checking whether a Ra machine is alive

### ISSUE THREAD

**Issue by gianluca-nitti** [rabbitmq/ra#172]
I think it would be useful to have one - or both - of these features:
1. a way to monitor a Ra machine/cluster, from a regular process, to get a message when the cluster goes down (for example, a crash happens while processing a command or the machine is stopped via `delete_cluster/1`)
2. a reliable way to programmatically check whether a Ra machine is alive (it can process commands).

Right now, for 2 I'm using `local_query/2` with a dummy query function returning a constant atom `alive` and matching the result against `{ok, {_, alive}, _}`, which mostly works, but there is a catch: if I do this immediately after stopping the machine with `delete_cluster/1`, the process calling `local_query/2` exits. 
I found out this is caused by the internals of `gen_statem`: [the client API](https://github.com/erlang/otp/blob/master/lib/stdlib/src/gen.erl#L202) puts a monitor on the state machine process. So if `local_query`, which uses `gen_statem:call`, is called right before the machine terminates, the `receive` block in `gen:do_call` (source linked above) gets the `:DOWN` and calls `exit`, terminating the process which was trying to query.

Alternatively, I was considering to either monitor or check via `erlang:process_info/1` each server of the cluster and see if the majority is online, however I'm not sure whether it would be a good approach to do this in the user application instead of inside the Ra library (open to opinions though).

**Comment by michaelklishin** [comment]
The definition of "alive" varies from system to system, so using an appropriate query type is by far the most flexible options. This is even more involved for multi-node systems. We have seen this time and time again with RabbitMQ itself. This library really should not be in the business of trying to provide "one true health check" because that thing does not exist.

If you have ideas about how monitoring of Ra node processes could be simplified, we'd welcome a pull request with a specific suggestion.

**Comment by michaelklishin** [comment]
Checking if a majority is online is not going to be very useful in the presence of partial partitions. A healthy Raft-based system is ultimately a system that can make progress and that means

 * There must be an elected leader
 * It must be able to reach the majority of nodes

but a single cluster node, including the leader, cannot determine this at any given point without, well, performing a query. This is also why monitoring individual nodes only makes so much sense, e.g. on the Erlang node that runs a certain Ra node (e.g. a quorum queue in RabbitMQ) to know when you have to shut down.

An event notification mechanism attached to a certain node can produce false positives. E.g. a node can assume that there's an ongoing election and notify your app about that but if the rest of the cluster disagrees, it would not be very helpful.

Unfortunately a single node in a Raft cluster can only say so much about the state of the system.
