### ISSUE TITLE
fetch failed in win 

### ISSUE THREAD

**Issue by iloveai8** [rabbitmq/ra#193]
===> Version cached at c:/Users/Administrator/.cache/rebar3/hex/hexpm/packages/gen_batch_server-0.8.4.tar is up to date, reusing it
===> Failed to fetch and copy dep: {pkg,<<"gen_batch_server">>,<<"0.8.4">>,
                                   <<"20535E9DBD4DC234E63B3DF79BA65D8A770396B2CAD6B4068A1E37E3AE010900">>,
                                   #{api_url => <<"https://hex.pm/api">>,
                                     http_adapter => hex_http_httpc,
                                     http_adapter_config =>
                                         #{profile => rebar},
                                     http_user_agent_fragment =>
                                         <<"(rebar3/3.8.0+build.4268.refc934ccca) (httpc)">>,
                                     name => <<"hexpm">>,
                                     repo_name => <<"hexpm">>,
                                     repo_public_key =>
                                         <<"-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEApqREcFDt5vV21JVe2QNB\nEdvzk6w36aNFhVGWN5toNJRjRJ6m4hIuG4KaXtDWVLjnvct6MYMfqhC79HAGwyF+\nIqR6Q6a5bbFSsImgBJwz1oadoVKD6ZNetAuCIK84cjMrEFRkELtEIPNHblCzUkkM\n3rS9+DPlnfG8hBvGi6tvQIuZmXGCxF/73hU0/MyGhbmEjIKRtG6b0sJYKelRLTPW\nXgK7s5pESgiwf2YC/2MGDXjAJfpfCd0RpLdvd4eRiXtVlE9qO9bND94E7PgQ/xqZ\nJ1i2xWFndWa6nfFnRxZmCStCOZWYYPlaxr+FZceFbpMwzTNs4g3d4tLNUcbKAIH4\n0wIDAQAB\n-----END PUBLIC KEY-----">>,
                                     repo_url => <<"https://repo.hex.pm">>,
                                     repo_verify => true,
                                     repo_verify_origin => true}}

**Comment by michaelklishin** [comment]
I cannot reproduce.
