### ISSUE TITLE
inconsistent `ra_leaderboard:lookup_members/1` output

### ISSUE THREAD

**Issue by prax-dev** [rabbitmq/ra#210]
Hello there,

In our project we are using `ra` for configuration management. As par use case we need the List of Cluster Members inside `ra_machine:apply/3` callback to explicitly verify integrity of changes within cluster members. We have planned to use `ra_leaderboard:lookup_members/1` to get List of all Members, but output is inconsistent.

Here are the smallest possible example to reproduce behaviour,

```erlang
%% Starting Seed Node

%% rebar3 shell --name ra_seed@`$hostname`

ra:start().

ClusterName = quick_start.
Machine = {simple, fun erlang:'+'/2, 0}.
ServerId=[{ra_server, node()}].

{ok, ServersStarted, _ServersNotStarted} = ra:start_cluster(ClusterName, Machine, ServerId)
``` 

Starting and Adding Cluster Members -
```erlang

%% rebar3 shell --name ra1@`$hostname`

ra:start().

ClusterName = quick_start.
Machine =  {simple, fun erlang:'+'/2, 0}.
UId = ra:new_uid(ra_lib:to_binary(ClusterName)).

Conf = #{ id => {ra_server, node()},
                   uid => UId,
                   cluster_name => ClusterName,
                   log_init_args => #{uid => UId},
                   initial_members => [],
                   machine => Machine}.
            
ra:start_server(Conf).

rpc:call('ra_seed@host', ra, add_member,[[{ra_server, 'ra1@hostname'}], {ra_server, node()}]).
```

Adding one more Node, 

```erlang

%% rebar3 shell --name ra2@`$hostname`

ra:start().

ClusterName = quick_start.
Machine =  {simple, fun erlang:'+'/2, 0}.
UId = ra:new_uid(ra_lib:to_binary(ClusterName)).

Conf = #{ id => {ra_server, node()},
                   uid => UId,
                   cluster_name => ClusterName,
                   log_init_args => #{uid => UId},
                   initial_members => [],
                   machine => Machine}.
            
ra:start_server(Conf).

rpc:call('ra_seed@host', ra, add_member,[[{ra_server, 'ra1@hostname'}], {ra_server, node()}]).
```

And the output of  `ra_leaderboard:lookup_members/1`  are -

On `ra_seed` Node,

```erlang
ra_leaderboard:lookup_members(quick_start).
% => [{ra_server,'ra_seed@hostname'}]
```

On `ra1` node,

```erlang
ra_leaderboard:lookup_members(quick_start).
% => [{ra_server,'ra_seed@hostname'},
% =>  {ra_server,'ra1@hostname'}]

```

And on `ra2` node,

```erlang
ra_leaderboard:lookup_members(quick_start).

% => [{ra_server,'ra_seed@hostname'},
% =>  {ra_server,'ra1@hostname'},
% =>  {ra_server,'ra2@hostname'}
]
```

Is this an expected behaviour ?

What are the other way to get list of Cluster Member inside `ra_machine:apply/3` callback ?

Warm regards,
/prakash

**Comment by michaelklishin** [comment]
`ra_leaderboard` was introduced for efficient looks up of the current leader for a Ra cluster (#166) by its (cluster) name.
It queries a local ETS table for that. The leaderboard is updated when cluster leadership changes (in `ra_server_proc:record_leader_change/2`), not when cluster members change.

There is `ra:members/1` and `ra:members/2`. They will issue a leader call.

I'm pretty sure Ra machines are not generally expected to perform leader calls.

**Comment by michaelklishin** [comment]
Instead of "explicitly verifying integrity" after Ra, consider using `ra:members/2` in your own code and trusting it. It returns
the value that is correct according to the quorum of nodes at the time of the call.

Or design your state machine to not depend on the exact list of members.

**Comment by prax-dev** [comment]
In our case we need to guarantee that command has been processed by each Cluster Member. How to ensure that command has been executed by all cluster member ?

Is there a way to change Quorum size ?

**Comment by michaelklishin** [comment]
@prax-dev in Raft, an operation is considered to be successful if a quorum of replicas has successfully applied and committed it. There is no way to guarantee that all of them did, and you probably don't want that (that would result in pretty bad availability guarantees).

Quorum is "more than half of cluster members". It changes together with the size of the cluster. Which, by the way, in Ra effectively must be 3 or more nodes. Two node clusters are explicitly not supported because there is no such thing as a majority in case those nodes disconnect.

**Comment by michaelklishin** [comment]
@dcorbacho and @kjnilsson confirm that if a Ra machine callback tries to do a leader call, that will deadlock (because Ra replica is calling the `apply/2` function. So this approach is not going to work.

**Comment by kjnilsson** [comment]
Why do you need to guarantee that all members have processed the command? To me this looks like sacrificing availability. I guess I don't fully understand your use case. if you want the list of current members to be processed by the raft state machine you could spawn a process that calls `ra:members/1` and then send a command with the result to the Ra leader.

**Comment by kjnilsson** [comment]
One thing that you will know that when a command has been processed successfully (a quorum) any followers that haven't yet applied the command will do so, eventually.

**Comment by prax-dev** [comment]
The use case which I'm talking about is the Business logic configuration management. Like, Cluster member should reject 'x' type of transactions. To achieve this, Leader will get a request from Admin Console to update configuration, and we need a guarantee that all Cluster member has processed the command. Because of its Financial System.

**Comment by michaelklishin** [comment]
@prax-dev Raft by definition assumes that applying a state transition on a majority of nodes is enough and is what "consensus" means. Requiring every replica to confirm will have terrible availability characteristics as @kjnilsson mentioned: you won't be able to tolerate a failure of a single node (which will inevitably happen).

With Raft, all replicas will **eventually** process the command, including after failure and recovery (and catch-up with the current leader). You can have a coordinator process that asks every cluster member of its view of certain state. Ra really doesn't expect that you would query an arbitrary member but you can (in at least some cases, the operation will be redirected to the leader).

It sounds like you would be better off not using Ra and querying all nodes directly until all of them confirm or some time out.

**Comment by prax-dev** [comment]
Thanks @michaelklishin @kjnilsson :+1:
