### ISSUE TITLE
Handle `nosuspend` when sending applied notifications.

### ISSUE THREAD

**Issue by kjnilsson** [rabbitmq/ra#248]
https://github.com/rabbitmq/ra/blob/main/src/ra_server_proc.erl#L1150

**Comment by pjk25** [comment]
Can we not just ignore the result as I presume notifications are do not have a requirement of delivery?

**Comment by pjk25** [comment]
Do I understand it correctly that `notify` is a built-in effect, though not documented in https://github.com/rabbitmq/ra/blob/main/docs/internals/INTERNALS.md ?

**Comment by kjnilsson** [comment]
Done in #260
