### ISSUE TITLE
ra_cluster_name type has to be an atom

### ISSUE THREAD

**Issue by adrianroe** [rabbitmq/ra#252]
```erlang
%% a friendly name for the cluster
-type ra_cluster_name() :: binary() | string() | atom().
```

In practice is seems that the name has to be an atom and is used to register a local process.  I do wonder if this causes potential issues with consumption of the atom table for very long running servers, but either way the type documentation and the observed behaviour don't currently align.

**Comment by kjnilsson** [comment]
The `ra_cluster_name()` isn't used to register the local process, instead we use the first element of the `ra_server_id()`.
