### ISSUE TITLE
Badmatch and undefined_reply errors

### ISSUE THREAD

**Issue by xinhaoyuan** [rabbitmq/ra#28]
Hi,

I've been using my tool [1] to find concurrency errors in ra. So far I've got some bugs and I think there are two that I can confirm:

1. When a ra cluster is reconfiguring, the leader could receive messages from servers that are not in the current cluster config of the leader state. According to ra_server.erl:322, the leader will still try to get the server information from the cluster config, which would trigger a `badmatch` error and crash the leader.

2. When a ra server receives `request_vote_rpc` message in `await_condition` state, ra_server.erl:826 will make transition of the state into `follower`, and turn the call rpc into a cast. This will trigger an `undefined_reply` error as the follower state is expecting the message with the `{call, From}` information.

[1]: https://github.com/xinhaoyuan/morpheus-app-test

**Comment by michaelklishin** [comment]
Can you please provide a set of steps to reproduce?

**Comment by xinhaoyuan** [comment]
In the `ra_test_f775c65` directory of https://github.com/xinhaoyuan/morpheus-app-test, you can reproduce by running
```
TESTCASE=inconsistent_state_2 make eunit t=ra_test | tee [SOME_OUTPUT_FILE]
```
This test case runs the `inconsistent_state_2` function in ra_test.erl to concurrently change cluster configuration and trigger leader election.
Within few runs you should be able to grep `badmatch` or `undefined_reply` in the log.

Note that once you find the errors, you can reproduce them by using the same testing seed in the log, for example:
```
SEED_TERM="{exrop,[77786557868068621|97756798991356137]}." TESTCASE=inconsistent_state_2 make eunit t=ra_test | tee [SOME_OUTPUT_FILE]
```

**Comment by xinhaoyuan** [comment]
Here are the reproducing test cases without my tool:

1. https://github.com/xinhaoyuan/morpheus-app-test/tree/master/ra_test_f775c65_repro_1
2. https://github.com/xinhaoyuan/morpheus-app-test/tree/master/ra_test_f775c65_repro_2

**Comment by kjnilsson** [comment]
Thank you. I will take a closer look once I finish the current stream of work. I _think_ 1. has been addressed in my branch but will verify once it is merged.

**Comment by michaelklishin** [comment]
We think this has been addressed.
