### ISSUE TITLE
Badkey error of `previous_cluster`

### ISSUE THREAD

**Issue by xinhaoyuan** [rabbitmq/ra#33]
Hi,

This is for the bug I posted on the mail list: https://groups.google.com/d/msg/rabbitmq-users/-YJyg2OztmU/M3k57gDbBQAJ.

Here is a reproducing test for this:
https://github.com/xinhaoyuan/morpheus-app-test/tree/master/ra_test_f775c65_repro_3

**Comment by michaelklishin** [comment]
I believe this has been investigated and addressed.
