### ISSUE TITLE
what's missing for a release?

### ISSUE THREAD

**Issue by benoitc** [rabbitmq/ra#34]
Seems like #9 is resolved. (though that retired version could be probably skipped).  What's missing for the release. Anything I can help?

**Comment by michaelklishin** [comment]
We have some RabbitMQ master QA to do against this version of Ra. After that we can produce a pre-1.0 release. It was decided that RabbitMQ will continue using Ra master after that as we expect reasonably quick evolution of both Ra and how we use it.

@kjnilsson anything to add?

**Comment by kjnilsson** [comment]
I think we can get 0.9.2 (current Ra master) published soon. I just need to make sure the rebar3 config is correct and do a bit of local testing.

**Comment by benoitc** [comment]
@kjnilsson  #35 would need to be merged before it.

About the rebar3 support, you will need to have `rabbitmq-ct-helpers` also supporting it if you want to run the tests. See  rabbitmq/rabbitmq-ct-helpers#23 about it.

**Comment by benoitc** [comment]
with the following additional patch to rebar using my repository all tests pass:
```erlang
diff --git rebar.config rebar.config
index a726f51..950df42 100644
--- rebar.config
+++ rebar.config
@@ -6,13 +6,9 @@
 {profiles,
  [{test, [{deps, [proper,
                   meck,
-                  elvis,
-                  {looking_glass,
-                   {git, "https://github.com/rabbitmq/looking-glass.git",
-                    {branch, "master"}}}%,
-%                  {rabbitmq_ct_helpers,
-%                    {git, "https://github.com/rabbitmq/rabbitmq-ct-helpers",
-%                     {branch, "master"}}}
+                 {rabbitmq_ct_helpers,
+                    {git, "https://github.com/benoitc/rabbitmq-ct-helpers",
+                     {branch, "rebar3-support"}}}
                  ]}]}
  ]
 }.```

result of the tests
```
 → rebar3 ct
===> Verifying dependencies...
===> Fetching rabbitmq_ct_helpers ({git,
                                           "https://github.com/benoitc/rabbitmq-ct-helpers",
                                           {branch,"rebar3-support"}})
===> Fetching rabbit_common ({pkg,<<"rabbit_common">>,<<"3.7.9">>})
===> Version cached at /Users/benoitc/.cache/rebar3/hex/hexpm/packages/rabbit_common-3.7.9.tar is up to date, reusing it
===> Fetching jsx ({pkg,<<"jsx">>,<<"2.9.0">>})
===> Version cached at /Users/benoitc/.cache/rebar3/hex/hexpm/packages/jsx-2.9.0.tar is up to date, reusing it
===> Fetching lager ({pkg,<<"lager">>,<<"3.6.5">>})
===> Version cached at /Users/benoitc/.cache/rebar3/hex/hexpm/packages/lager-3.6.5.tar is up to date, reusing it
===> Fetching ranch ({pkg,<<"ranch">>,<<"1.6.2">>})
===> Version cached at /Users/benoitc/.cache/rebar3/hex/hexpm/packages/ranch-1.6.2.tar is up to date, reusing it
===> Fetching ranch_proxy_protocol ({pkg,<<"ranch_proxy_protocol">>,
                                            <<"2.1.1">>})
===> Version cached at /Users/benoitc/.cache/rebar3/hex/hexpm/packages/ranch_proxy_protocol-2.1.1.tar is up to date, reusing it
===> Fetching recon ({pkg,<<"recon">>,<<"2.3.6">>})
===> Version cached at /Users/benoitc/.cache/rebar3/hex/hexpm/packages/recon-2.3.6.tar is up to date, reusing it
===> Fetching goldrush ({pkg,<<"goldrush">>,<<"0.1.9">>})
===> Version cached at /Users/benoitc/.cache/rebar3/hex/hexpm/packages/goldrush-0.1.9.tar is up to date, reusing it
===> Compiling ranch
===> Compiling ranch_proxy_protocol
===> Compiling gen_batch_server
===> Compiling recon
===> Compiling goldrush
===> Compiling lager
===> Compiling jsx
===> Compiling rabbit_common
===> Compiling rabbitmq_ct_helpers
===> Compiling aten
===> Compiling meck
===> Compiling ra
===> Running Common Test suites...
%%% coordination_SUITE: =INFO REPORT==== 4-Dec-2018::15:24:06.522800 ===
WAL: recovering []
... <CUT>

=WARNING REPORT==== 4-Dec-2018::15:24:31.028819 ===
ra: {start_cluster_minority,'s1@Benoits-iPro'} terminating with shutdown in state pre_vote

.
%%% partitions_SUITE: .
%%% ra_2_SUITE: .........
%%% ra_SUITE: ......................
%%% ra_directory_SUITE: ..
%%% ra_log_2_SUITE: ...........................
%%% ra_log_SUITE: ..............
%%% ra_log_meta_SUITE: ..
%%% ra_log_props_SUITE: ......................
%%% ra_log_segment_SUITE: ..........
%%% ra_log_segment_writer_SUITE: .........
%%% ra_log_snapshot_SUITE: ......
%%% ra_log_snapshot_writer_SUITE: ..
%%% ra_log_wal_SUITE: ........................
%%% ra_machine_ets_SUITE: .
%%% ra_machine_int_SUITE: .........
%%% ra_props_SUITE: .
%%% ra_server_SUITE: ........................................
All 209 tests passed.
```

**Comment by benoitc** [comment]
@kjnilsson maybe just having `inet_tcp_proxy` internal would be enough?

**Comment by kjnilsson** [comment]
ok a release is out so closing this. Thanks :)
