### ISSUE TITLE
Check queue existence before writing WAL to segment

### ISSUE THREAD

**Issue by johkin** [rabbitmq/ra#348]
If qourum-queue is deleted before the WAL content is written to the segment-file, a warning is issued:
`"segment_writer: failed to open segment file /var/lib/rabbitmq/mnesia/rabbit@granskontroll-rabbitmq01.**/quorum/rabbit@granskontroll-rabbitmq01.**/2F_RES7UVV437CY2HA/00000001.segment error: enoent"
"segment_writer: skipping segment as directory /var/lib/rabbitmq/mnesia/rabbit@granskontroll-rabbitmq01.**/quorum/rabbit@granskontroll-rabbitmq01.**/2F_RES7UVV437CY2HA does not exist"`

A check for queue existence here
https://github.com/rabbitmq/ra/blob/main/src/ra_log_segment_writer.erl#L384
would be good.

**Comment by kjnilsson** [comment]
That is pretty much how it does the check atm, if the directory isn't there it assumes the Ra server is gone and skips it. That said, we could do a check somewhere around [https://github.com/rabbitmq/ra/blob/main/src/ra_log_segment_writer.erl#L224](here) to see if the ServerUId
is registered in the `ra_directory` - I'd still like to log something when we detect orphaned data in the WAL.

For now lowering the log message to debug would be a quick improvement.

**Comment by johkin** [comment]
Maybe the issue heading could be modified to "Modify log-level for segment-writer" to better describe the change?
