### ISSUE TITLE
RFC: remove list of effects from ra_machine:apply/4

### ISSUE THREAD

**Issue by kjnilsson** [rabbitmq/ra#38]
`ra_machine:apply/4` takes a list of effects as it's 3rd argument. This is done for efficiency so that all effects in a batch of commands are cons-ed to the list, avoiding any list concatenation. The list of effects is then reversed at the end of the apply batch and executed.

This does mean that implementors of `ra_machine` need to return the effects for a single command in the reverse order they want them actioned. I think this isn't a great API and would like to remove the effects from the `apply/4` function making it `apply/3` and accept the effects from in the order they should be implemented. I think we can do this efficiently by simply gather effects in a nested list rather than a flat list. this would also machines to return single effects without wrapping them into a list.

I also suggest optionally moving the reply to the second slot in the return tuple allowing implementors to leave out the effects all together.

Current signature:

```
-callback 'apply'(command_meta_data(), command(), effects(), State) ->
    {State, effects(), reply()}.
```

Proposed signature:

```
-callback 'apply'(command_meta_data(), command(), State) ->
    {State, reply(), effect() | [effect()]} | {State, reply()}.
```

WDYT @hairyhum @michaelklishin @dcorbacho @benoitc @acogoluegnes

**Comment by hairyhum** [comment]
`This does mean that implementors of ra_machine need to return the effects for a single command in the reverse order they want them actioned.`
This is not clear from the docs. I'm all for changing that.

I would expect lists of effects to be relatively short and should not impact the performance enough to require confusing APIs.

**Comment by kjnilsson** [comment]
Both the api docs and the state machine tutorial state that the list of effects is reversed before processing.

Batching levels can get very high inside ra under throughout and some state machines may emit hundreds if not thousands of effects for a single command so it’s well worth trying to optimise but I think it can be done differently.

**Comment by hairyhum** [comment]
`Ra will reverse the list of effects before processing.` phrase is not clear. It tells you that some list will be reversed, but does not explain in which order they will be processed. Anyway [1, 2, 3] order is better then [3, 2, 1].

What kind of machine would issue hundreds of effects?

**Comment by kjnilsson** [comment]
`rabbit_fifo` in rabbitmq-server could issue thousands of `send_msg` effects

**Comment by hairyhum** [comment]
OK. Fair enough.

**Comment by benoitc** [comment]
i think i like the simplicity of such new signature. +1 for the change. Also potentially it can helps to improve the back pressure imo.

**Comment by kjnilsson** [comment]
PR: https://github.com/rabbitmq/ra/pull/42

reviews welcome
