### ISSUE TITLE
ra_client module

### ISSUE THREAD

**Issue by kjnilsson** [rabbitmq/ra#5]
To allow users to simply interact with a `ra` cluster and provide linearizable semantics (§6.3 in raft thesis) we should provide a `ra_client` module to track session state and so on.

**Comment by kjnilsson** [comment]
done

**Comment by jingxu2021** [comment]
Didn't find ra_client.erl. Where's it? This is really a good idea, so we can know what's happening internally. Thanks.

**Comment by michaelklishin** [comment]
> Didn't find ra_client.erl. Where's it? This is really a good idea, so we can know what's happening internally. Thanks.

`ra`, `ra_server` and `ra_leaderboard` are the most relevant modules for "clients" that use Ra (Ra is a library for implementing Raft-based state machines, not a server).
