### ISSUE TITLE
hex.pm release pipeline

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/ra#9]
We are getting to the point where it would be beneficial to both team RabbitMQ and other potential users if Ra was available via hex.pm, perhaps as `-dev` versions first.

**Comment by michaelklishin** [comment]
We are in the process of migrating an existing hex.pm project named `ra` to our org. This may take some time.

**Comment by michaelklishin** [comment]
Our team now has control over the `ra` project on Hex.pm (major props to the original author) and we plan on producing a release fairly soon.

**Comment by kjnilsson** [comment]
We can use `rebar3 hex cut` to increment versions and push to hex.pm so closing this.
