### ISSUE TITLE
Disaster recovery

### ISSUE THREAD

**Issue by deadtrickster** [rabbitmq/ra#93]
Sorry if I missed this in the docs...

How to perform disaster recovery with default log module?:
 - What and when to backup;
 - How to do cold restart having that backup?

Thanks

**Comment by michaelklishin** [comment]
We plan to introduce a "passive follower" role that can accumulate and truncate the log but not apply any effects. In many cases starting a node with an existing log directory and set of peers would be enough but it's something we haven't investigated in details.

**Comment by michaelklishin** [comment]
I believe this is effectively a duplicate of #44.
